import type { ViewKey, UserRole } from './store'

export interface ModuleConfig {
  key: ViewKey
  title: string
  shortTitle: string
  description: string
  icon: string // lucide icon name
  category: 'operations' | 'academic' | 'ai' | 'administration' | 'engagement' | 'infrastructure'
  color: string // tailwind gradient
  accent: string // hex
  aiPowered: boolean
  availableTo: UserRole[]
  features: string[]
  stats?: { label: string; value: string; trend?: string }[]
}

export const MODULES: ModuleConfig[] = [
  {
    key: 'dashboard',
    title: 'Command Center',
    shortTitle: 'Dashboard',
    description: 'AI-powered unified command center with real-time KPIs, predictive insights, and intelligent alerts across all school operations.',
    icon: 'LayoutDashboard',
    category: 'operations',
    color: 'from-blue-600 to-blue-800',
    accent: '#1E3A8A',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'SCHOOL_HEAD', 'ADMIN', 'TEACHER', 'STUDENT', 'PARENT', 'RECEPTION', 'IT_TEAM'],
    features: ['Live KPIs', 'AI Insights', 'Predictive Analytics', 'Smart Alerts', 'Role-based View', 'Voice Commands'],
    stats: [
      { label: 'Active Students', value: '2,847', trend: '+4.2%' },
      { label: 'Staff Online', value: '186', trend: '+1.8%' },
      { label: 'Fee Collection', value: '₹4.8Cr', trend: '+12.5%' },
      { label: 'Attendance', value: '94.2%', trend: '+0.8%' },
    ],
  },
  {
    key: 'front-desk',
    title: 'Front Desk & Entry Management',
    shortTitle: 'Front Desk',
    description: 'AI receptionist with visitor tracking, smart entry passes, OTP verification, and automated gate pass generation.',
    icon: 'ConciergeBell',
    category: 'operations',
    color: 'from-blue-600 to-blue-800',
    accent: '#1E3A8A',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'RECEPTION', 'SCHOOL_HEAD'],
    features: ['Visitor Check-In', 'Smart Gate Pass', 'OTP Verification', 'AI Face Capture', 'Visitor History', 'Appointment Booking'],
    stats: [
      { label: 'Visitors Today', value: '47', trend: '+12%' },
      { label: 'Pending Approvals', value: '3', trend: '-2' },
      { label: 'Avg Check-in Time', value: '42s', trend: '-18%' },
      { label: 'Gate Passes Issued', value: '128', trend: '+8%' },
    ],
  },
  {
    key: 'admissions',
    title: 'Admission Management',
    shortTitle: 'Admissions',
    description: 'End-to-end admission workflow with AI prospect scoring, document verification, online forms, and kindergarten registration analytics.',
    icon: 'UserPlus',
    category: 'operations',
    color: 'from-blue-600 to-blue-800',
    accent: '#1E3A8A',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'RECEPTION', 'SCHOOL_HEAD'],
    features: ['Online Application', 'AI Prospect Scoring', 'Document Vault', 'Interview Scheduler', 'KG Analytics', 'Waitlist Management', 'Auto-Notification'],
    stats: [
      { label: 'Applications (2026-27)', value: '1,284', trend: '+24%' },
      { label: 'Confirmed Seats', value: '612', trend: '+18%' },
      { label: 'KG Registrations', value: '184', trend: '+32%' },
      { label: 'Conversion Rate', value: '68.5%', trend: '+5.2%' },
    ],
  },
  {
    key: 'attendance',
    title: 'Attendance & Leave Management',
    shortTitle: 'Attendance',
    description: 'Multi-modal attendance via biometric, RFID, face recognition, with AI leave prediction and auto-substitution triggers.',
    icon: 'Fingerprint',
    category: 'operations',
    color: 'from-blue-600 to-blue-800',
    accent: '#1E3A8A',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD', 'RECEPTION'],
    features: ['Biometric', 'RFID Card', 'Face Recognition', 'Auto SMS to Parents', 'Leave Workflow', 'AI Anomaly Detection', 'Compensatory Off'],
    stats: [
      { label: 'Today Present', value: '2,683', trend: '94.2%' },
      { label: 'Absent', value: '164', trend: '5.8%' },
      { label: 'Late Arrivals', value: '47', trend: '+3' },
      { label: 'On Leave', value: '23', trend: '-5' },
    ],
  },
  {
    key: 'fees',
    title: 'Online Fee & Finance Tracking',
    shortTitle: 'Fees',
    description: 'AI-powered fee collection with UPI/Card/Net-banking, automatic reminders, defaulter prediction, and scholarship recommendations.',
    icon: 'Wallet',
    category: 'administration',
    color: 'from-sky-500 to-sky-700',
    accent: '#0EA5E9',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'SCHOOL_HEAD', 'PARENT'],
    features: ['Online Payments', 'Auto Reminders', 'Defaulter AI Prediction', 'Scholarship Engine', 'GST Invoices', 'Installment Plans', 'Refund Workflow'],
    stats: [
      { label: 'Collected (FY)', value: '₹4.82 Cr', trend: '+12.5%' },
      { label: 'Pending', value: '₹38.4 L', trend: '-8.2%' },
      { label: 'Defaulters', value: '47', trend: '-12' },
      { label: 'Online vs Cash', value: '92:8', trend: '+3%' },
    ],
  },
  {
    key: 'academic',
    title: 'Academic Management',
    shortTitle: 'Academics',
    description: 'Complete academic operations: curriculum mapping, portion tracking, lesson plan sync, syllabus coverage analytics with AI insights.',
    icon: 'BookOpen',
    category: 'academic',
    color: 'from-teal-600 to-teal-800',
    accent: '#0D9488',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD'],
    features: ['Curriculum Mapping', 'Syllabus Tracker', 'Lesson Plan Sync', 'Coverage Analytics', 'AI Content Suggester', 'Smart Homework'],
    stats: [
      { label: 'Avg Coverage', value: '76%', trend: '+4%' },
      { label: 'Lesson Plans', value: '1,847', trend: '+128' },
      { label: 'Pending Topics', value: '234', trend: '-12' },
      { label: 'AI Suggestions Used', value: '892', trend: '+34%' },
    ],
  },
  {
    key: 'examinations',
    title: 'Examination & Result System',
    shortTitle: 'Exams',
    description: 'Complete exam lifecycle: scheduling, hall arrangements, invigilation, OMR evaluation, scorecards, and AI-powered result analytics.',
    icon: 'FileText',
    category: 'academic',
    color: 'from-teal-600 to-teal-800',
    accent: '#0D9488',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD', 'STUDENT', 'PARENT'],
    features: ['Exam Scheduler', 'Hall Arrangement', 'Invigilation Duty', 'OMR Scanning', 'AI Score Verification', 'Report Cards', 'Parent SMS'],
    stats: [
      { label: 'Upcoming Exams', value: '14', trend: '7 days' },
      { label: 'Papers Evaluated', value: '8,492', trend: '+1,284' },
      { label: 'Avg Score', value: '78.4%', trend: '+2.1%' },
      { label: 'Pass Rate', value: '96.8%', trend: '+1.4%' },
    ],
  },
  {
    key: 'ai-academic',
    title: 'AI Academic Intelligence',
    shortTitle: 'AI Academic',
    description: 'Predictive learning analytics, at-risk student identification, performance forecasting, and personalized intervention recommendations.',
    icon: 'BrainCircuit',
    category: 'ai',
    color: 'from-orange-500 to-orange-700',
    accent: '#F97316',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD'],
    features: ['At-Risk Prediction', 'Learning Style Detection', 'Performance Forecast', 'Intervention Recommender', 'Cohort Comparison', 'Auto Remedial Plans'],
    stats: [
      { label: 'At-Risk Students', value: '124', trend: '-18' },
      { label: 'AI Interventions', value: '342', trend: '+47' },
      { label: 'Improvement Rate', value: '72%', trend: '+8%' },
      { label: 'Predictions Accuracy', value: '91.4%', trend: '+2.1%' },
    ],
  },
  {
    key: 'canteen',
    title: 'Canteen Management',
    shortTitle: 'Canteen',
    description: 'Smart canteen with pre-ordering, QR-based pickup, cashless payments, AI menu optimization, and dietary tracking.',
    icon: 'UtensilsCrossed',
    category: 'infrastructure',
    color: 'from-amber-500 to-amber-700',
    accent: '#D97706',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'STUDENT', 'TEACHER', 'PARENT'],
    features: ['Pre-Order Menu', 'QR Pickup', 'Cashless Wallet', 'AI Menu Optimizer', 'Dietary Tags', 'Inventory Sync', 'Waste Tracking'],
    stats: [
      { label: 'Orders Today', value: '847', trend: '+12%' },
      { label: 'Revenue Today', value: '₹18,420', trend: '+8%' },
      { label: 'Avg Wait Time', value: '3.2 min', trend: '-22%' },
      { label: 'Waste Reduced', value: '34%', trend: '+6%' },
    ],
  },
  {
    key: 'transport',
    title: 'Transport & Bus Tracking',
    shortTitle: 'Transport',
    description: 'Live GPS tracking, route optimization, AI ETA prediction, RF-ID boarding, and parent pickup alerts with geo-fencing.',
    icon: 'Bus',
    category: 'infrastructure',
    color: 'from-amber-500 to-amber-700',
    accent: '#D97706',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'PARENT', 'RECEPTION'],
    features: ['Live GPS', 'Route Optimizer', 'AI ETA', 'RFID Boarding', 'Speed Alerts', 'Driver App', 'Parent Notifications', 'Geo-fencing'],
    stats: [
      { label: 'Buses Running', value: '38', trend: 'All Active' },
      { label: 'Students Onboard', value: '1,847', trend: '94%' },
      { label: 'On-Time Arrival', value: '96.2%', trend: '+1.4%' },
      { label: 'Routes Optimized', value: '12', trend: 'AI saved 18%' },
    ],
  },
  {
    key: 'biometric',
    title: 'Biometric / RFID / Face Camera',
    shortTitle: 'Biometric',
    description: 'Unified biometric infrastructure: fingerprint, RFID cards, AI face recognition cameras with anti-spoofing and mask detection.',
    icon: 'ScanFace',
    category: 'infrastructure',
    color: 'from-amber-500 to-amber-700',
    accent: '#D97706',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'IT_TEAM', 'RECEPTION'],
    features: ['Face Recognition', 'Fingerprint', 'RFID Cards', 'Anti-Spoof AI', 'Mask Detection', 'Multi-Device Sync', 'Offline Fallback'],
    stats: [
      { label: 'Devices Online', value: '47', trend: '100%' },
      { label: 'Today Scans', value: '8,492', trend: '+8%' },
      { label: 'Avg Recognition', value: '0.4s', trend: '-12%' },
      { label: 'Spoofing Blocked', value: '3', trend: 'AI caught' },
    ],
  },
  {
    key: 'communication',
    title: 'Communication & Notifications',
    shortTitle: 'Communication',
    description: 'Omnichannel messaging: SMS, email, push, in-app, WhatsApp Business with AI message personalization and translation.',
    icon: 'MessageSquare',
    category: 'engagement',
    color: 'from-rose-500 to-rose-700',
    accent: '#E11D48',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD', 'RECEPTION'],
    features: ['Bulk SMS', 'Email Campaigns', 'WhatsApp Business', 'Push Notifications', 'AI Personalization', 'Multi-lingual', 'Auto Translation', 'Drip Campaigns'],
    stats: [
      { label: 'Messages Sent Today', value: '4,892', trend: '+18%' },
      { label: 'Delivery Rate', value: '98.7%', trend: '+0.4%' },
      { label: 'Read Rate', value: '84.2%', trend: '+3.2%' },
      { label: 'AI Personalized', value: '67%', trend: '+12%' },
    ],
  },
  {
    key: 'events',
    title: 'Events & Calendar',
    shortTitle: 'Events',
    description: 'Centralized event calendar with AI scheduling conflict detection, automated invitations, RSVP tracking, and venue management.',
    icon: 'CalendarDays',
    category: 'engagement',
    color: 'from-rose-500 to-rose-700',
    accent: '#E11D48',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD', 'STUDENT', 'PARENT'],
    features: ['Master Calendar', 'AI Conflict Detection', 'Auto Invitations', 'RSVP Tracking', 'Venue Booking', 'Reminder Engine', 'Recurring Events'],
    stats: [
      { label: 'Events This Month', value: '34', trend: '+8' },
      { label: 'Upcoming (7 days)', value: '12', trend: '3 today' },
      { label: 'Avg Attendance', value: '87%', trend: '+4%' },
      { label: 'Conflicts Resolved', value: '7', trend: 'AI caught' },
    ],
  },
  {
    key: 'activities',
    title: 'Extra-curricular & Activities',
    shortTitle: 'Activities',
    description: 'Sports, arts, robotics, music, dance tracking with AI talent identification, performance analytics, and competition management.',
    icon: 'Trophy',
    category: 'engagement',
    color: 'from-rose-500 to-rose-700',
    accent: '#E11D48',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'STUDENT', 'PARENT'],
    features: ['Activity Catalog', 'AI Talent ID', 'Performance Tracker', 'Competition Mgmt', 'Coach Allocation', 'Achievement Records', 'Skill Tree'],
    stats: [
      { label: 'Active Clubs', value: '24', trend: '+3' },
      { label: 'Enrolled Students', value: '1,892', trend: '+8%' },
      { label: 'Competitions Won', value: '47', trend: '+12' },
      { label: 'AI Talent Identified', value: '128', trend: '+24' },
    ],
  },
  {
    key: 'report-cards',
    title: 'Report Cards, Certificates & PTM',
    shortTitle: 'Report Cards',
    description: 'AI-generated report cards with holistic grading, digital signatures, certificate issuance, and PTM scheduling with smart agendas.',
    icon: 'Award',
    category: 'academic',
    color: 'from-teal-600 to-teal-800',
    accent: '#0D9488',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD', 'STUDENT', 'PARENT'],
    features: ['AI Report Generation', 'Digital Signatures', 'Holistic Grading', 'Certificate Engine', 'PTM Scheduler', 'Smart Agendas', 'Parent Feedback'],
    stats: [
      { label: 'Reports Generated', value: '2,847', trend: '+184' },
      { label: 'Certificates Issued', value: '892', trend: '+47' },
      { label: 'PTM Scheduled', value: '38', trend: 'This week' },
      { label: 'Parent Feedback', value: '4.7/5', trend: '+0.2' },
    ],
  },
  {
    key: 'documents',
    title: 'Document Management',
    shortTitle: 'Documents',
    description: 'Secure digital vault with AI OCR, auto-categorization, version control, e-signatures, and compliance tracking.',
    icon: 'FolderLock',
    category: 'administration',
    color: 'from-sky-500 to-sky-700',
    accent: '#0EA5E9',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'IT_TEAM', 'RECEPTION'],
    features: ['AI OCR', 'Auto-Categorize', 'Version Control', 'E-Signatures', 'Compliance Tracker', 'Bulk Upload', 'Smart Search'],
    stats: [
      { label: 'Documents Stored', value: '184K', trend: '+2.4K' },
      { label: 'AI Indexed', value: '94%', trend: '+3%' },
      { label: 'Pending Verification', value: '47', trend: '-12' },
      { label: 'Storage Used', value: '142 GB', trend: '+8 GB' },
    ],
  },
  {
    key: 'security',
    title: 'Security & Compliance',
    shortTitle: 'Security',
    description: 'AI-powered campus security: CCTV analytics, intrusion detection, fire alerts, data encryption, and DPDP/GDPR compliance.',
    icon: 'ShieldCheck',
    category: 'administration',
    color: 'from-sky-500 to-sky-700',
    accent: '#0EA5E9',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'IT_TEAM', 'SCHOOL_HEAD'],
    features: ['CCTV AI Analytics', 'Intrusion Detection', 'Fire/Smoke Alerts', 'Data Encryption', 'DPDP/GDPR Compliance', 'Audit Logs', 'Role-Based Access'],
    stats: [
      { label: 'CCTV Cameras', value: '184', trend: 'All Online' },
      { label: 'Alerts Today', value: '4', trend: '-2' },
      { label: 'Avg Response', value: '1.2 min', trend: '-18%' },
      { label: 'Compliance Score', value: '98.4%', trend: '+0.6%' },
    ],
  },
  {
    key: 'admin-engine',
    title: 'Admin & Automation Engine',
    shortTitle: 'Automation',
    description: 'No-code workflow builder, AI process automation, scheduled tasks, trigger-based actions, and integration orchestration.',
    icon: 'Cog',
    category: 'administration',
    color: 'from-sky-500 to-sky-700',
    accent: '#0EA5E9',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'IT_TEAM'],
    features: ['No-Code Workflows', 'AI Process Automation', 'Trigger Engine', 'Scheduler', 'Webhooks', 'Integration Hub', 'Audit Trail'],
    stats: [
      { label: 'Active Workflows', value: '247', trend: '+12' },
      { label: 'Tasks Automated', value: '8.4K', trend: 'This month' },
      { label: 'Time Saved', value: '342 hrs', trend: '+18%' },
      { label: 'Success Rate', value: '99.4%', trend: '+0.2%' },
    ],
  },
  {
    key: 'ai-behavior',
    title: 'AI Behavior & Learning Tracking',
    shortTitle: 'AI Behavior',
    description: 'AI-powered behavior analysis, engagement tracking, learning pattern detection, and performance evaluation across cohorts.',
    icon: 'Brain',
    category: 'ai',
    color: 'from-orange-500 to-orange-700',
    accent: '#F97316',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD'],
    features: ['Engagement Tracking', 'Behavior Analysis', 'Learning Patterns', 'Cohort Evaluation', 'AI Recommendations', 'Wellness Alerts'],
    stats: [
      { label: 'Avg Engagement', value: '85%', trend: '+3%' },
      { label: 'Behavior Anomalies', value: '12', trend: '-4' },
      { label: 'Wellness Alerts', value: '7', trend: 'Resolved' },
      { label: 'AI Insights Generated', value: '847', trend: '+128' },
    ],
  },
  {
    key: 'parent-portal',
    title: 'Parent Engagement Portal',
    shortTitle: 'Parent Portal',
    description: '360° parent visibility: child progress, attendance, fees, homework, PTM, real-time bus tracking, and AI-driven insights.',
    icon: 'Users',
    category: 'engagement',
    color: 'from-rose-500 to-rose-700',
    accent: '#E11D48',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'PARENT'],
    features: ['Child Dashboard', 'Real-time Updates', 'Fee Payment', 'Homework View', 'PTM Booking', 'Bus Tracking', 'AI Insights', 'Multi-Child'],
    stats: [
      { label: 'Active Parents', value: '2,612', trend: '+84' },
      { label: 'Daily Logins', value: '1,847', trend: '+12%' },
      { label: 'Engagement Rate', value: '78%', trend: '+4%' },
      { label: 'Satisfaction', value: '4.6/5', trend: '+0.1' },
    ],
  },
  {
    key: 'timetable',
    title: 'Smart Timetable & Calendar',
    shortTitle: 'Timetable',
    description: 'AI-generated timetables with conflict resolution, teacher availability, subject priority, and automatic substitution.',
    icon: 'CalendarClock',
    category: 'academic',
    color: 'from-teal-600 to-teal-800',
    accent: '#0D9488',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD'],
    features: ['AI Timetable Generator', 'Conflict Resolver', 'Teacher Availability', 'Substitution Engine', 'Room Allocation', 'Break Optimizer', 'Mobile Sync'],
    stats: [
      { label: 'Classes Scheduled', value: '847', trend: 'Weekly' },
      { label: 'Conflicts Resolved', value: '24', trend: 'AI caught' },
      { label: 'Substitutions Today', value: '7', trend: '+2' },
      { label: 'Teacher Utilization', value: '87%', trend: '+3%' },
    ],
  },
  {
    key: 'curriculum',
    title: 'Curriculum & Subject Mapping',
    shortTitle: 'Curriculum',
    description: 'Curriculum framework design, LO mapping, skill taxonomy, AI content suggestions, and cross-grade alignment.',
    icon: 'Library',
    category: 'academic',
    color: 'from-teal-600 to-teal-800',
    accent: '#0D9488',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD'],
    features: ['Curriculum Framework', 'LO Mapping', 'Skill Taxonomy', 'AI Content', 'Cross-Grade Alignment', 'CBSE/ICSE/IB/State', 'Mapping Audit'],
    stats: [
      { label: 'Subjects Mapped', value: '47', trend: 'All boards' },
      { label: 'Learning Outcomes', value: '1,847', trend: '+128' },
      { label: 'AI Content Suggested', value: '892', trend: '+47' },
      { label: 'Coverage Audit', value: '94%', trend: '+2%' },
    ],
  },
  {
    key: 'health',
    title: 'Health & Wellness Tracking',
    shortTitle: 'Health',
    description: 'Student health records, BMI tracking, vaccination drives, mental wellness surveys, and AI early-warning alerts.',
    icon: 'HeartPulse',
    category: 'engagement',
    color: 'from-rose-500 to-rose-700',
    accent: '#E11D48',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'PARENT', 'SCHOOL_HEAD'],
    features: ['Health Records', 'BMI Tracking', 'Vaccination Drive', 'Mental Wellness', 'AI Early Warning', 'Medical Inventory', 'Emergency Contacts'],
    stats: [
      { label: 'Health Records', value: '2,847', trend: '+84' },
      { label: 'Vaccinated', value: '94%', trend: '+2%' },
      { label: 'Wellness Score', value: '8.4/10', trend: '+0.2' },
      { label: 'AI Alerts', value: '12', trend: 'Resolved' },
    ],
  },
  {
    key: 'hostel',
    title: 'Hostel Management',
    shortTitle: 'Hostel',
    description: 'Hostel allocation, room management, mess menu, visitor logs, leave passes, and AI occupancy optimization.',
    icon: 'Building2',
    category: 'infrastructure',
    color: 'from-amber-500 to-amber-700',
    accent: '#D97706',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'SCHOOL_HEAD', 'RECEPTION'],
    features: ['Room Allocation', 'Mess Management', 'Visitor Log', 'Leave Pass', 'AI Occupancy', 'Maintenance', 'Laundry Service', 'Warden App'],
    stats: [
      { label: 'Hostels', value: '4', trend: '2 Boys / 2 Girls' },
      { label: 'Occupancy', value: '94.2%', trend: '+2%' },
      { label: 'Residents', value: '847', trend: '+12' },
      { label: 'Mess Rating', value: '4.3/5', trend: '+0.2' },
    ],
  },
  {
    key: 'alumni',
    title: 'Alumni Network',
    shortTitle: 'Alumni',
    description: 'Alumni database, mentor matching, donation drives, reunion events, and AI-driven networking suggestions.',
    icon: 'GraduationCap',
    category: 'engagement',
    color: 'from-rose-500 to-rose-700',
    accent: '#E11D48',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'SCHOOL_HEAD'],
    features: ['Alumni Database', 'Mentor Match AI', 'Donation Drive', 'Reunion Planner', 'Job Board', 'Networking Suggestions', 'Newsletter'],
    stats: [
      { label: 'Registered Alumni', value: '12,847', trend: '+248' },
      { label: 'Active Mentors', value: '342', trend: '+18' },
      { label: 'Donations (FY)', value: '₹84 L', trend: '+18%' },
      { label: 'Reunions (Year)', value: '14', trend: '+3' },
    ],
  },
  {
    key: 'hrms',
    title: 'HRMS & Payroll',
    shortTitle: 'HRMS',
    description: 'Complete staff lifecycle: recruitment, onboarding, attendance, leave, payroll, PF/ESI, appraisals, and AI attrition prediction.',
    icon: 'UserCog',
    category: 'administration',
    color: 'from-sky-500 to-sky-700',
    accent: '#0EA5E9',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'SCHOOL_HEAD', 'IT_TEAM'],
    features: ['Recruitment', 'Onboarding', 'Attendance', 'Leave Mgmt', 'Payroll Engine', 'PF/ESI', 'Appraisals', 'AI Attrition Prediction'],
    stats: [
      { label: 'Total Staff', value: '186', trend: '+4' },
      { label: 'Payroll Processed', value: '₹62.4 L', trend: 'This month' },
      { label: 'Attrition Risk', value: '4', trend: 'AI flagged' },
      { label: 'Avg Appraisal', value: '8.4%', trend: '+1.2%' },
    ],
  },
  {
    key: 'finance',
    title: 'Financial & Accounting',
    shortTitle: 'Finance',
    description: 'Double-entry accounting, budget tracking, vendor management, GST filing, and AI cash-flow forecasting.',
    icon: 'Landmark',
    category: 'administration',
    color: 'from-sky-500 to-sky-700',
    accent: '#0EA5E9',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'SCHOOL_HEAD'],
    features: ['Double-Entry Books', 'Budget Tracker', 'Vendor Mgmt', 'GST Filing', 'AI Cash Forecast', 'Bank Reconciliation', 'Audit Ready'],
    stats: [
      { label: 'Annual Budget', value: '₹18.4 Cr', trend: 'FY 26-27' },
      { label: 'YTD Spent', value: '₹4.2 Cr', trend: '23%' },
      { label: 'Vendors Active', value: '184', trend: '+12' },
      { label: 'AI Forecast Accuracy', value: '94%', trend: '+2%' },
    ],
  },
  {
    key: 'ai-calendar',
    title: 'AI Academic Calendar & Substitution',
    shortTitle: 'AI Calendar',
    description: 'AI-powered academic calendar with daily/weekly/monthly planning, syllabus tracking, lesson sync, and intelligent substitution engine.',
    icon: 'CalendarRange',
    category: 'ai',
    color: 'from-orange-500 to-orange-700',
    accent: '#F97316',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD'],
    features: ['Daily/Weekly/Monthly View', 'AI Substitution Engine', 'Subject Expert Matching', 'Free Teacher Auto-Allocation', 'Lesson Plan Sync', 'Coverage Tracking', 'Smart Notifications'],
    stats: [
      { label: 'Coverage Today', value: '98.2%', trend: '+1.4%' },
      { label: 'AI Substitutions', value: '12', trend: 'Today' },
      { label: 'Avg Allocation Time', value: '4.2s', trend: '-82%' },
      { label: 'Subject Match Accuracy', value: '96%', trend: '+2%' },
    ],
  },
  {
    key: 'ai-question-paper',
    title: 'AI Question Paper Generator',
    shortTitle: 'AI Question Paper',
    description: 'AI-generated question papers with blueprint adherence, difficulty calibration, MCQ/subjective mix, and auto-answer keys.',
    icon: 'FileQuestion',
    category: 'ai',
    color: 'from-orange-500 to-orange-700',
    accent: '#F97316',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'SCHOOL_HEAD'],
    features: ['Blueprint Adherence', 'Difficulty Calibration', 'MCQ + Subjective', 'Auto Answer Key', 'Question Bank AI', 'Plagiarism Check', 'Multi-Board Support'],
    stats: [
      { label: 'Papers Generated', value: '847', trend: '+128' },
      { label: 'Question Bank', value: '24K+', trend: '+2.4K' },
      { label: 'Avg Generation Time', value: '8.2s', trend: '-34%' },
      { label: 'Blueprint Accuracy', value: '98%', trend: '+1%' },
    ],
  },
  {
    key: 'ai-career',
    title: 'AI Career Counselling',
    shortTitle: 'AI Career',
    description: 'Psychometric assessment, aptitude analysis, AI career path recommendation, and mentor matching for students Grade 8-12.',
    icon: 'Compass',
    category: 'ai',
    color: 'from-orange-500 to-orange-700',
    accent: '#F97316',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'STUDENT', 'PARENT', 'SCHOOL_HEAD'],
    features: ['Psychometric Test', 'Aptitude Analysis', 'AI Career Match', 'Stream Selection', 'College Predictor', 'Mentor Matching', 'Skill Roadmap'],
    stats: [
      { label: 'Students Counseled', value: '1,247', trend: '+184' },
      { label: 'Avg Match Score', value: '87%', trend: '+3%' },
      { label: 'Mentors Available', value: '342', trend: '+24' },
      { label: 'Satisfaction', value: '4.8/5', trend: '+0.1' },
    ],
  },
  {
    key: 'ai-safety',
    title: 'AI Real-time Safety Alert',
    shortTitle: 'AI Safety',
    description: 'AI vision-based real-time safety: fight detection, fall detection, fire/smoke, intrusion, and instant multi-channel alerts.',
    icon: 'Siren',
    category: 'ai',
    color: 'from-orange-500 to-orange-700',
    accent: '#F97316',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'SCHOOL_HEAD', 'IT_TEAM'],
    features: ['Fight Detection', 'Fall Detection', 'Fire/Smoke AI', 'Intrusion Alert', 'Crowd Density', 'Multi-Channel Alert', 'Auto-Escalation', 'Drill Mode'],
    stats: [
      { label: 'Cameras AI-Enabled', value: '184', trend: '100%' },
      { label: 'Alerts Today', value: '4', trend: '-2' },
      { label: 'Avg Response', value: '1.2 min', trend: '-18%' },
      { label: 'False Positives', value: '0.8%', trend: '-0.3%' },
    ],
  },
  {
    key: 'ai-mock',
    title: 'AI Preparation Mock Engine',
    shortTitle: 'AI Mock Engine',
    description: 'AI-generated mock tests, adaptive difficulty, weak-area targeting, performance analytics, and personalized study plans.',
    icon: 'Target',
    category: 'ai',
    color: 'from-orange-500 to-orange-700',
    accent: '#F97316',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'TEACHER', 'STUDENT', 'PARENT'],
    features: ['Adaptive Mock Tests', 'Weak-Area Targeting', 'AI Study Plan', 'Performance Analytics', 'Question Bank', 'Timer Mode', 'Solutions AI'],
    stats: [
      { label: 'Mock Tests Taken', value: '8,492', trend: '+1,284' },
      { label: 'Avg Score Improvement', value: '+18%', trend: '+3%' },
      { label: 'Active Learners', value: '2,184', trend: '+248' },
      { label: 'AI Study Plans', value: '1,847', trend: '+184' },
    ],
  },
  {
    key: 'rag-knowledge',
    title: 'RAG Knowledge Base',
    shortTitle: 'RAG Knowledge',
    description: 'Vector-indexed knowledge base powering all AI features: policies, SOPs, circulars, syllabus, and historical data.',
    icon: 'Database',
    category: 'ai',
    color: 'from-orange-500 to-orange-700',
    accent: '#F97316',
    aiPowered: true,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'IT_TEAM'],
    features: ['Vector Indexing', 'Semantic Search', 'Policy Vault', 'SOP Repository', 'Auto Embeddings', 'Source Citations', 'Multi-Format Ingest'],
    stats: [
      { label: 'Documents Indexed', value: '14,847', trend: '+248' },
      { label: 'Vector Dimensions', value: '1,536', trend: 'text-embedding-3' },
      { label: 'Avg Query Time', value: '0.4s', trend: '-12%' },
      { label: 'Retrieval Accuracy', value: '94.2%', trend: '+1.4%' },
    ],
  },
  {
    key: 'settings',
    title: 'Settings & Configuration',
    shortTitle: 'Settings',
    description: 'System-wide configuration: roles, permissions, integrations, branding, workflows, and AI model preferences.',
    icon: 'Settings',
    category: 'administration',
    color: 'from-sky-500 to-sky-700',
    accent: '#0EA5E9',
    aiPowered: false,
    availableTo: ['SUPER_ADMIN', 'ADMIN', 'IT_TEAM'],
    features: ['Role-Based Access', 'Permission Matrix', 'Integration Hub', 'Branding Studio', 'Workflow Builder', 'AI Model Config', 'Audit Logs'],
    stats: [
      { label: 'Active Integrations', value: '24', trend: '+2' },
      { label: 'Roles Configured', value: '12', trend: '8 active' },
      { label: 'API Calls Today', value: '184K', trend: '+12%' },
      { label: 'System Uptime', value: '99.98%', trend: '30-day' },
    ],
  },
]

export const ROLE_INFO: Record<UserRole, { label: string; description: string; color: string; icon: string }> = {
  SUPER_ADMIN: { label: 'Super Admin', description: 'Full system access across all schools & modules', color: 'from-orange-500 to-orange-700', icon: 'Crown' },
  SCHOOL_HEAD: { label: 'School Head', description: 'Principal / Director with full school oversight', color: 'from-blue-600 to-blue-800', icon: 'GraduationCap' },
  ADMIN: { label: 'Administrator', description: 'Day-to-day administrative operations', color: 'from-blue-500 to-blue-700', icon: 'ShieldCheck' },
  TEACHER: { label: 'Teacher', description: 'Class teacher with academic & attendance tools', color: 'from-teal-500 to-teal-700', icon: 'BookOpen' },
  STUDENT: { label: 'Student', description: 'Personalized learning dashboard & resources', color: 'from-sky-500 to-blue-700', icon: 'User' },
  PARENT: { label: 'Parent', description: 'Child progress, fees, attendance & communication', color: 'from-rose-500 to-rose-700', icon: 'Users' },
  RECEPTION: { label: 'Reception', description: 'Front desk, visitors & admission support', color: 'from-amber-500 to-orange-700', icon: 'ConciergeBell' },
  IT_TEAM: { label: 'IT Team', description: 'Infrastructure, security & system configuration', color: 'from-slate-600 to-slate-800', icon: 'Server' },
}

// Demo accounts for instant login
export const DEMO_ACCOUNTS: { role: UserRole; email: string; password: string; name: string }[] = [
  { role: 'SUPER_ADMIN', email: 'superadmin@learnx.ai', password: 'demo1234', name: 'Arjun Mehta' },
  { role: 'SCHOOL_HEAD', email: 'principal@learnx.ai', password: 'demo1234', name: 'Dr. Priya Sharma' },
  { role: 'ADMIN', email: 'admin@learnx.ai', password: 'demo1234', name: 'Rajesh Kumar' },
  { role: 'TEACHER', email: 'teacher@learnx.ai', password: 'demo1234', name: 'Anita Verma' },
  { role: 'STUDENT', email: 'student@learnx.ai', password: 'demo1234', name: 'Aarav Singh' },
  { role: 'PARENT', email: 'parent@learnx.ai', password: 'demo1234', name: 'Sunita Reddy' },
  { role: 'RECEPTION', email: 'reception@learnx.ai', password: 'demo1234', name: 'Meena Iyer' },
  { role: 'IT_TEAM', email: 'it@learnx.ai', password: 'demo1234', name: 'Vikram Nair' },
]
