import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { getUserFromHeaders, enforceAction } from '@/lib/apiScope'

export const runtime = 'nodejs'

function generateInstallmentRows(count: number, academicYear: string, amount: number): string {
  const monthsMap: Record<number, number[]> = { 3: [3, 6, 9], 6: [3, 5, 7, 9, 11, 1], 9: [3, 4, 5, 6, 7, 8, 9, 10, 11], 12: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1] }
  const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  const months = monthsMap[count] || [3]
  const startYear = parseInt(academicYear.split('-')[0].split('/').pop() || '2026')
  let rows = ''
  for (let i = 0; i < count; i++) {
    const monthIdx = months[i] || months[i % months.length]
    const year = monthIdx < 3 ? startYear + 1 : startYear
    const dueDate = `${monthNames[monthIdx]} 15, ${year}`
    rows += `<tr><td style="padding:8px;border-bottom:1px solid #e2e8f0;">${i + 1}</td><td style="padding:8px;border-bottom:1px solid #e2e8f0;">${dueDate}</td><td style="padding:8px;border-bottom:1px solid #e2e8f0;text-align:right;">₹${amount.toLocaleString('en-IN')}</td></tr>`
  }
  return rows
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = getUserFromHeaders(req)
    const check = enforceAction('fee', 'view', user)
    if (!check.allowed) return NextResponse.json({ success: false, error: check.reason }, { status: 403 })
    const { id } = await params
    const body = await req.json().catch(() => ({}))
    const structure = await db.feeStructure.findUnique({ where: { id } })
    if (!structure || structure.schoolId !== user.schoolId) return NextResponse.json({ success: false, error: 'Not found' }, { status: 404 })
    const addOns = JSON.parse(structure.addOns || '[]')
    const addOnsTotal = addOns.reduce((s: number, a: any) => s + a.amount, 0)
    const grossTotal = structure.baseFee + addOnsTotal
    const discount = structure.installmentCount === 1 ? Math.round(grossTotal * 0.05) : 0
    const addOnRows = addOns.map((a: any, i: number) => `<tr><td style="padding:10px;border-bottom:1px solid #eee;">${a.icon || '📌'} ${a.name}</td><td style="padding:10px;border-bottom:1px solid #eee;text-align:right;">₹${a.amount.toLocaleString('en-IN')}</td><td style="padding:10px;border-bottom:1px solid #eee;text-align:center;">${a.isOptional ? 'Optional' : 'Mandatory'}</td></tr>`).join('')
    const html = `<!DOCTYPE html><html><head><title>Fee Structure — ${structure.grade}</title><style>@page{margin:25mm 20mm;size:A4}body{font-family:Georgia,serif;color:#1e293b;line-height:1.6}.page{max-width:700px;margin:0 auto;padding:30px;border:2px solid #1E3A8A;border-radius:12px}.header{text-align:center;padding-bottom:20px;border-bottom:3px double #1E3A8A;margin-bottom:25px}.header h1{color:#1E3A8A;font-size:24px}table{width:100%;border-collapse:collapse;margin:10px 0}th{background:#1E3A8A;color:white;padding:10px;font-size:11px;text-align:left}.total-row{font-weight:bold;background:#f0fdf4}</style></head><body><div class="page"><div class="header"><h1>LearnX International School</h1><p>Fee Structure — Academic Year ${structure.academicYear}</p></div><div style="display:flex;justify-content:space-between;margin-bottom:15px"><div><strong>Grade:</strong> ${structure.grade}</div><div><strong>Plan:</strong> ${structure.installmentCount} installments</div></div><table><thead><tr><th>Item</th><th style="text-align:right">Amount</th><th style="text-align:center">Type</th></tr></thead><tbody><tr><td style="padding:10px;border-bottom:1px solid #eee"><strong>Base Tuition Fee (Annual)</strong></td><td style="padding:10px;border-bottom:1px solid #eee;text-align:right">₹${structure.baseFee.toLocaleString('en-IN')}</td><td style="padding:10px;border-bottom:1px solid #eee;text-align:center">Mandatory</td></tr>${addOnRows}<tr class="total-row"><td style="padding:12px 10px">Total Annual Fee</td><td style="padding:12px 10px;text-align:right">₹${structure.totalFee.toLocaleString('en-IN')}</td><td></td></tr></tbody></table>${structure.installmentCount > 1 ? `<table style="margin-top:15px"><thead><tr><th>#</th><th>Due Date</th><th style="text-align:right">Amount</th></tr></thead><tbody>${generateInstallmentRows(structure.installmentCount, structure.academicYear, structure.totalPerInstallment)}</tbody></table>` : ''}${structure.notes ? `<div style="margin-top:15px;padding:10px;background:#f8fafc;border-radius:8px"><strong>Notes:</strong> ${structure.notes}</div>` : ''}<p style="text-align:center;margin-top:30px;color:#64748b;font-size:11px">Generated by LearnX Fee Management System on ${new Date().toLocaleString('en-IN')}</p></div></body></html>`
    return new NextResponse(html, { headers: { 'Content-Type': 'text/html', 'Content-Disposition': `inline; filename="Fee-Structure-${structure.grade}.html"` } })
  } catch (e: any) { return NextResponse.json({ success: false, error: e?.message }, { status: 500 }) }
}
