'use client'
import { SectionHeader } from './SectionHeader'
export function HRMSModuleEnhanced() { return <div className="p-8"><SectionHeader emoji="👔" title="HRMS & Staff Management" accent="#1E3A8A" /><div className="mt-6 p-5 rounded-xl bg-white border border-slate-200"><p className="text-sm text-slate-600">HRMS module loading...</p></div></div> }
export function ConcernsModule() { return <div className="p-8"><SectionHeader emoji="⚠️" title="Student Concerns" accent="#E11D48" /><div className="mt-6 p-5 rounded-xl bg-white border border-slate-200"><p className="text-sm text-slate-600">Concerns module loading...</p></div></div> }
export function SISModule() { return <div className="p-8"><SectionHeader emoji="📊" title="Student Information System" accent="#0D9488" /><div className="mt-6 p-5 rounded-xl bg-white border border-slate-200"><p className="text-sm text-slate-600">SIS module loading...</p></div></div> }
export function DiaryModule() { return <div className="p-8"><SectionHeader emoji="📔" title="Daily Diary" accent="#8B5CF6" /><div className="mt-6 p-5 rounded-xl bg-white border border-slate-200"><p className="text-sm text-slate-600">Diary module loading...</p></div></div> }
export function PhotoGalleryModule() { return <div className="p-8"><SectionHeader emoji="📸" title="Photo Gallery" accent="#EC4899" /><div className="mt-6 p-5 rounded-xl bg-white border border-slate-200"><p className="text-sm text-slate-600">Gallery module loading...</p></div></div> }
export function PTMSchedulerModule() { return <div className="p-8"><SectionHeader emoji="🤝" title="PTM Scheduler" accent="#7C3AED" /><div className="mt-6 p-5 rounded-xl bg-white border border-slate-200"><p className="text-sm text-slate-600">PTM module loading...</p></div></div> }
export function CertificateEngineModule() { return <div className="p-8"><SectionHeader emoji="🏆" title="Certificate Engine" accent="#F59E0B" /><div className="mt-6 p-5 rounded-xl bg-white border border-slate-200"><p className="text-sm text-slate-600">Certificate module loading...</p></div></div> }
export function ActivitiesModule() { return <div className="p-8"><SectionHeader emoji="🏆" title="Extracurricular & Activities" accent="#10B981" /><div className="mt-6 p-5 rounded-xl bg-white border border-slate-200"><p className="text-sm text-slate-600">Activities module loading...</p></div></div> }
export function AlumniModule() { return <div className="p-8"><SectionHeader emoji="🎓" title="Alumni Network" accent="#6366F1" /><div className="mt-6 p-5 rounded-xl bg-white border border-slate-200"><p className="text-sm text-slate-600">Alumni module loading...</p></div></div> }
